# cliente=[
#     {
#         "codigo_cliente":0,
#         "nombre_cliente":"",
#         "nombre_contacto":"",
#         "apellido_contacto":"",
#         "telefono":"",
#         "fax":"",
#         "linea_direccion1":"",
#         "linea_direccion2":"",
#         "ciudad":"",
#         "region":"",
#         "pais":"",
#         "codigo_postal":"",
#         "codigo_empleado_rep_ventas":0,
#         "limite_credito":1.0,
# }
# ]

