empleado=[
    {
        "codigo_empleado":0,
        "nombre":"",
        "apellido1":"",
        "apellido2":"",
        "extension":"",
        "email":"",
        "codigo_oficina":"",
        "codigo_jefe":0,
        "puesto":"",
    }
]