oficina=[
    {
        "codigo_oficina":"",
        "ciudad":"",
        "pais":"",
        "region":"",
        "codigo_postal":"",
        "telefono":"",
        "linea_direccion1":"",
        "linea_direccion2":"",
}
]